# Site settings
title: Valerie
email: valerie@example.com
description: > # this means to ignore newlines until "baseurl:"
  Photographer
baseurl: /valerie # the subpath of your site, e.g. /blog/
url: # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/

